S02 us33 page association
WildCodeSchool/orleans-202109-php-projet-rocs pull request #133
Opened 2021-11-09 16:21 UTC by cedric-pardon

2021-11-09 16:33 UTC, Halphane submitted a review, later dismissed

2021-11-09 16:44 UTC, sblondeau requested changes
ton fichier office.css est vide, inutile de le garder non ?

2021-11-09 16:44 UTC, sblondeau commented on src/View/Office/office.html.twig
> +            <div class="card bg-light mb-3 mb-5 p-0" style="width: 18rem;">
style inline à retirer

2021-11-10 09:28 UTC, Halphane approved these changes

2021-11-10 09:41 UTC, sblondeau approved these changes

2021-11-10 09:41 UTC, merged