S02 us02 header home
WildCodeSchool/orleans-202109-php-projet-rocs pull request #138
Opened 2021-11-10 10:46 UTC by Bsir-Rachida

2021-11-10 13:23 UTC, cedric-pardon submitted a review, later dismissed

2021-11-10 14:22 UTC, Bsir-Rachida commented
en cours

2021-11-11 11:05 UTC, Halphane requested changes

2021-11-11 11:05 UTC, Halphane commented on src/View/Home/index.html.twig
> +					<p class="text-center m-5 mb-0">Technique et style le patinage artistique, associe la danse, la chorégraphie et la gymnastique. C’est un moyen d’expression corporelle fantastique.En Solo, en cou
C'est un text pour présenter les différentes activités du club et non une en particulière. Pour donner envie aux visisteurs de justement voir nos différentes activités

2021-11-14 10:11 UTC, Halphane approved these changes

2021-11-15 07:59 UTC, sblondeau approved these changes

2021-11-15 07:59 UTC, merged