S02 us20 create activity
WildCodeSchool/orleans-202109-php-projet-rocs pull request #140
Opened 2021-11-10 15:05 UTC by Halphane

2021-11-12 07:58 UTC, sblondeau requested changes

2021-11-12 07:58 UTC, sblondeau commented on src/View/admin/adminAddActivity.html.twig
> +                    <label for="schedule" class="form-label">Horraires</label>
Horaires

2021-11-12 07:58 UTC, sblondeau commented on src/View/admin/adminAddActivity.html.twig
> +                <button type="submit" class="btn btn-primary offset-5 col-2 mt-2">Envoyer</button>
juste pour info, tu peux mettre uniquement button, l'attribut type=submit est pas nécessaire pour un button à l'intérieur d'une balise form ;-)

2021-11-12 14:22 UTC, cedric-pardon approved these changes

2021-11-13 14:55 UTC, sblondeau approved these changes

2021-11-13 14:55 UTC, merged