We can delete an activity
WildCodeSchool/orleans-202109-php-projet-rocs pull request #141
Opened 2021-11-10 15:29 UTC by Halphane

2021-11-12 08:02 UTC, sblondeau requested changes

2021-11-12 08:02 UTC, sblondeau commented on src/Model/ActivityManager.php
> +    public function adminSelectAll(): array
y a t-il un vrai interet de faire un **admin**SelecAll(). Cette meme méthode ne va t-elle pas etre réutilisée pour la vue coté visiteur ? un selectAllWithTrainer() me paraitrait plus indiqué ?
idem en dessous, tu peux l'appeler juste delete() et pas adminDelete()

2021-11-12 14:23 UTC, cedric-pardon approved these changes

2021-11-13 14:57 UTC, sblondeau approved these changes

2021-11-15 09:20 UTC, cedric-pardon approved these changes

2021-11-15 09:50 UTC, merged