S02US43-Admin-trainer
WildCodeSchool/orleans-202109-php-projet-rocs pull request #143
Opened 2021-11-10 17:37 UTC by Bsir-Rachida

2021-11-11 01:26 UTC, Halphane requested changes

2021-11-11 01:26 UTC, Halphane commented on src/View/admin/adminTrainer.html.twig
> +						<th scope="col">Télèphone</th>
téléphone et non télèphone

2021-11-11 11:00 UTC, Halphane approved these changes

2021-11-12 08:06 UTC, sblondeau requested changes

2021-11-12 08:06 UTC, sblondeau commented on src/Controller/AdminTrainerController.php
> +        $trainersManager = new TrainerManager();
$trainerManager et pas $trainersManager

2021-11-12 08:06 UTC, sblondeau commented on src/Model/TrainerManager.php
> +    public function adminSelectAll(): array
pourquoi faire un adminSelectAll? aucune plus value pas rapport au selectAll() déjà dans l'AbstractManager
ce n'est pas parce que tu as des controlleur Admin que tu dois recréé des methode "admin" dans le manager, tu peux réutiliser les memes méthodes de manager pour les pages admin et non admin

2021-11-12 08:06 UTC, sblondeau commented on src/Model/TrainerManager.php
> +    public function adminSelectAll(): array
et pour le coup, selectAll() de base te permet d'ajouter un paramètre de tri, là tu pourrais dans ton controlleur trier par firstname ou lastname par ex

2021-11-14 10:13 UTC, Halphane approved these changes

2021-11-14 10:32 UTC, Halphane requested changes

2021-11-14 10:32 UTC, Halphane commented on src/Controller/AdminTrainerController.php
> +        $trainers = $trainerManager->SelectAll('lastname');
Même si les méthodes ne subissent pas la casse, c'est selectAll et non SelectAll

2021-11-15 08:56 UTC, Halphane submitted a review, later dismissed

2021-11-15 09:53 UTC, sblondeau requested changes

2021-11-15 09:53 UTC, sblondeau commented on src/View/admin/adminTrainer.html.twig
> +	<!--TODO Extend adminLayout-->
ce todo est inutile c'est fait non ?

2021-11-15 09:53 UTC, sblondeau commented on src/View/admin/adminTrainer.html.twig
> +								{{ trainer.firstname }}
attention tu as mis en entete nom/prénom (ce qui est logique vu que tu tries par lastname
mais dans le tableau tu as mis firstname/lastname (à inverser donc)

2021-11-15 10:27 UTC, Halphane submitted a review, later dismissed

2021-11-15 10:35 UTC, sblondeau approved these changes

2021-11-15 10:49 UTC, cedric-pardon approved these changes

2021-11-15 10:52 UTC, merged