S02 us31 admin connexion
WildCodeSchool/orleans-202109-php-projet-rocs pull request #155
Opened 2021-11-10 21:34 UTC by Halphane

2021-11-11 14:49 UTC, cedric-pardon approved these changes

2021-11-12 08:12 UTC, sblondeau requested changes
C'est pas mal ce que tu as fait mais il reste beaucoup de point problématique en terme de sécurité.
Et je pense que tu couvres trop de US d'un coup (genre le logout c'est une autre US)
Laisse là de coté pour le moment car elle est plus qu'optionnelle cette US, on en reparlera si tu es intéressé :-)

2021-11-12 08:12 UTC, sblondeau commented on src/Controller/AdminController.php
> +                        $errors['notFind'] = 'L\'utilisateur n\'a pas été trouver ou le mot de passe est éroné';
trouvé
erroné

2021-11-12 08:12 UTC, sblondeau commented on src/Controller/AdminController.php
> +        if (ini_get("session.use_cookies")) {
inutile     ton session_destroy suffit

2021-11-12 08:12 UTC, sblondeau commented on src/Controller/AdminController.php
> +    public function erreur(): string
error

2021-11-12 08:12 UTC, sblondeau commented on src/Model/AdminManager.php
> +        $statement->bindValue('password', $data['password'], \PDO::PARAM_STR);
le mot de passe doit etre hashé (fonction password_hash)

2021-11-12 08:12 UTC, sblondeau commented on src/View/admin/adminErreur.html.twig
> +                <h1 class="fs-2 m-0">Vous n'êtes pas connecter</h1>
connecté

2021-11-12 08:12 UTC, sblondeau commented on src/View/admin/adminErreur.html.twig
> +                    Pour aller sur ce site vous devez vous êtres authentifier ici
être

2021-11-12 08:12 UTC, sblondeau commented on src/View/adminLayout.html.twig
> +    <a href="/admin/deconnection" class="btn btn-danger">Déconnection</a>
Déconnexion

2021-11-12 08:12 UTC, sblondeau commented on src/Controller/AdminController.php
> +        $admins = $adminManager->selectAll();
tu ne devrais récup que le user correspondant au login entré

2021-11-12 14:25 UTC, cedric-pardon approved these changes

2021-11-15 08:12 UTC, sblondeau requested changes

2021-11-15 08:12 UTC, sblondeau commented on src/View/admin/adminError.html.twig
> +                    Pour aller sur ce site vous devez vous être authentifier ici
authentifié

2021-11-15 09:23 UTC, cedric-pardon approved these changes

2021-11-15 09:53 UTC, sblondeau submitted a review, later dismissed

2021-11-15 10:29 UTC, cedric-pardon approved these changes

2021-11-15 10:36 UTC, merged