S02 us44 add trainer
WildCodeSchool/orleans-202109-php-projet-rocs pull request #159
Opened 2021-11-12 21:39 UTC by Bsir-Rachida

2021-11-14 10:18 UTC, Halphane requested changes

2021-11-14 10:18 UTC, Halphane commented on src/Controller/AdminTrainerController.php
> +        $trainers = $trainersManager->SelectAll();
Même si les méthodes ne subissent pas la casse, c'est selectAll() et non SelectAll()

2021-11-14 10:18 UTC, Halphane commented on src/Controller/AdminTrainerController.php
> +            // if validation is ok, update and redirection
Enlève le TODO puisque  tu l'as fait

2021-11-14 10:35 UTC, Halphane requested changes
Tu as certainement copié/collé du code qui vient d'une autre branche. Il faut attendre que ta branche soit sur dev pour pouvoir tirer une branche depuis dev et faire tes autres pages

2021-11-14 10:35 UTC, Halphane commented on public/assets/css/admin/adminTrainers.css
> +thead {
Tu recréer un css d'une ta branche US43

2021-11-14 10:35 UTC, Halphane commented on src/Controller/AdminTrainerController.php
> +        $trainers = $trainersManager->SelectAll();
De plus tu recréer une method index

2021-11-14 10:35 UTC, Halphane commented on src/Controller/AdminTrainerController.php
> +<?php
Tu recréer ton controller alors qu'il est présent dans ta US43

2021-11-15 08:57 UTC, Halphane submitted a review, later dismissed

2021-11-15 09:55 UTC, sblondeau approved these changes

2021-11-15 10:50 UTC, cedric-pardon submitted a review, later dismissed

2021-11-15 11:05 UTC, cedric-pardon approved these changes

2021-11-15 11:07 UTC, merged