S02 us45 update trainer
WildCodeSchool/orleans-202109-php-projet-rocs pull request #161
Opened 2021-11-13 07:05 UTC by Bsir-Rachida

2021-11-14 10:22 UTC, Halphane requested changes

2021-11-14 10:22 UTC, Halphane commented on src/Controller/AdminTrainerController.php
> +            // if validation is ok, update and redirection
Enleve le todo

2021-11-14 10:22 UTC, Halphane commented on src/Model/TrainerManager.php
> +            `phoneNumber` = :phoneNumber , `email` = :email ,`gender` = :gender WHERE id=:id");
Je pense que créer un variable $query pour mettre dans la requête serait plus lisible

2021-11-14 10:23 UTC, Halphane commented
Utilise le même formulaire pour ajouter un entraîneur et pour le modifier, ce n'est pas dry sinon

2021-11-15 08:59 UTC, Halphane commented
Tu n'utilise pas le même formulaire pour ajouter ou modifier un entraîneur

2021-11-15 10:52 UTC, cedric-pardon submitted a review, later dismissed

2021-11-15 11:07 UTC, sblondeau submitted a review, later dismissed

2021-11-15 17:59 UTC, cedric-pardon approved these changes

2021-11-16 07:53 UTC, merged