query delete
WildCodeSchool/orleans-202109-php-projet-rocs pull request #162
Opened 2021-11-13 11:42 UTC by Bsir-Rachida

2021-11-14 10:29 UTC, Halphane requested changes
Tu ne dois pas copier/coller du code d'autre branche

2021-11-14 10:29 UTC, Halphane commented on public/assets/css/admin/adminTrainers.css
> +thead {
pourquoi du css pour supprimer un entraîneur

2021-11-14 10:29 UTC, Halphane commented on src/View/admin/adminTrainer.html.twig
> +{% extends "adminLayout.html.twig" %}
pourquoi tu recréer ta page trainer index ?

2021-11-14 10:29 UTC, Halphane commented on src/Controller/AdminTrainerController.php
> +    public function index(): string
Pourquoi tu recréer une méthode index que tu as déjà dans l'US 43

2021-11-14 10:29 UTC, Halphane commented on src/routes.php
> +    'admin/entraineur' => ['AdminTrainerController', 'index',],
idem

2021-11-15 09:00 UTC, Halphane approved these changes

2021-11-15 09:58 UTC, sblondeau requested changes

2021-11-15 09:58 UTC, sblondeau commented on src/View/admin/adminTrainer.html.twig
> +	<!--TODO Extend adminLayout-->
ligne à enlever

2021-11-15 09:58 UTC, sblondeau commented on src/View/admin/adminTrainer.html.twig
> +								{{ trainer.firstname }}
meme pb aussi car tu as copier/coller le meme code ou parti de la branche ?
je sais pas c'est pas tjs facile mais c'est mieux d'attendre que la 1ere PR soit passée dans ce cas

2021-11-15 10:54 UTC, cedric-pardon submitted a review, later dismissed

2021-11-15 11:08 UTC, sblondeau approved these changes

2021-11-15 17:59 UTC, cedric-pardon submitted a review, later dismissed

2021-11-16 11:24 UTC, cedric-pardon approved these changes

2021-11-16 13:00 UTC, merged