can modify an activity
WildCodeSchool/orleans-202109-php-projet-rocs pull request #164
Opened 2021-11-14 10:08 UTC by Halphane

2021-11-15 09:28 UTC, cedric-pardon approved these changes

2021-11-15 10:03 UTC, sblondeau requested changes

2021-11-15 10:03 UTC, sblondeau commented on src/Controller/AdminActivityController.php
> +            $count = 0;
hum je pense que tu peux faire plus optimisé avec un array_column / in_array

2021-11-15 10:03 UTC, sblondeau commented on src/Controller/AdminActivityController.php
> +        $trainers = $trainerManager->selectAll();
tri ton selectAll (selon lastname) pour avoir un select qui affiche les trainers dans l'ordre alphab

2021-11-15 10:43 UTC, cedric-pardon approved these changes

2021-11-15 18:00 UTC, cedric-pardon submitted a review, later dismissed

2021-11-16 07:54 UTC, sblondeau requested changes

2021-11-16 07:54 UTC, sblondeau commented on src/Controller/AdminActivityController.php
> +        $activityManager = new activityManager();
tjs pas modifié

2021-11-16 07:54 UTC, sblondeau commented on src/Controller/AdminActivityController.php
> +            $count = 0;
idem

2021-11-16 15:56 UTC, sblondeau approved these changes

2021-11-16 15:56 UTC, merged