ajout function index
WildCodeSchool/orleans-202109-php-projet-rocs pull request #171
Opened 2021-11-15 11:32 UTC by Bsir-Rachida

2021-11-15 18:01 UTC, cedric-pardon submitted a review, later dismissed

2021-11-16 07:59 UTC, sblondeau requested changes

2021-11-16 07:59 UTC, sblondeau commented on src/Controller/AdminTrainerController.php
> +        $trainersManager = new TrainerManager();
tri pas lastname

2021-11-16 11:25 UTC, cedric-pardon submitted a review, later dismissed

2021-11-16 13:01 UTC, sblondeau approved these changes

2021-11-16 15:21 UTC, cedric-pardon approved these changes

2021-11-16 15:38 UTC, Halphane approved these changes

2021-11-16 15:55 UTC, merged