S01 us05
WildCodeSchool/orleans-202109-php-projet-rocs pull request #23
Opened 2021-11-03 15:23 UTC by cedric-pardon

2021-11-03 16:28 UTC, Bsir-Rachida requested changes
ajouter le titre de la page

2021-11-03 16:31 UTC, Bsir-Rachida approved these changes

2021-11-03 21:36 UTC, Halphane approved these changes

2021-11-04 08:12 UTC, sblondeau requested changes

2021-11-04 08:12 UTC, sblondeau commented on src/routes.php
> +    'adhésion' => ['MembershipController', 'index',],
on etait presque bien :D j'ai faillit te l'accepter du premier coup !
mais il faut éviter les accents et caractères spéciaux dans les routes
adhésion => adhesion
et si tu as plusieurs "mots" tu les sépares par des tirets, ex : nous contacter => nous-contacter

2021-11-04 08:47 UTC, Halphane commented on src/routes.php
> +    'adhésion' => ['MembershipController', 'index',],
zut

2021-11-04 09:05 UTC, cedric-pardon commented on src/routes.php
> +    'adhésion' => ['MembershipController', 'index',],
ok c'est modifié

2021-11-04 09:22 UTC, Halphane approved these changes

2021-11-04 09:39 UTC, sblondeau approved these changes

2021-11-04 09:39 UTC, merged