footer html+css
WildCodeSchool/orleans-202109-php-projet-rocs pull request #25
Opened 2021-11-03 16:30 UTC by Bsir-Rachida

2021-11-03 21:29 UTC, Halphane requested changes

2021-11-03 21:29 UTC, Halphane commented on public/assets/css/style.css
> +@import url('footer.css');
Pourquoi import le footer dans le fichier css global ?

2021-11-03 21:29 UTC, Halphane commented on src/View/Include/_footer.html.twig
> +				<h4>Contacter nous</h4>
Contactez et non pas Contacter

2021-11-03 21:29 UTC, Halphane commented on src/View/Include/_footer.html.twig
> +						<button class="btn btn-footer" type="button">envoyer</button>
Pourquoi avoir mit des éléments d'un formulaire pour juste un email ?
(sur le wireframe il y avais juste une adresse email avec un logo a sa droite)

2021-11-03 21:29 UTC, Halphane commented on src/View/Include/_footer.html.twig
> +<div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2)">
Pas de style directement dans l'html

2021-11-03 21:29 UTC, Halphane commented on src/View/layout.html.twig
> +		<link rel="icon" href="/assets/images/favicon.png">
Deux appelles css sur une même ligne

2021-11-04 10:33 UTC, Halphane approved these changes
ça me paraît good

2021-11-04 11:37 UTC, sblondeau requested changes

2021-11-04 11:37 UTC, sblondeau commented on src/View/Include/_footer.html.twig
> +				<br><br>
pas de br pour gérer les espace verticaux, seulement pour faire des retours à la ligne dans un paragraphe de texte, si tu peux tu margin, fais du CSS ;-) (et utilise préférentiellement les classes de bootstrap)

2021-11-04 11:37 UTC, sblondeau commented on src/View/Include/_footer.html.twig
> +				<br>
idem

2021-11-04 11:37 UTC, sblondeau commented on src/View/Include/_footer.html.twig
> +				<br>
idem (voir plus bas)

2021-11-04 15:10 UTC, sblondeau submitted a review, later dismissed

2021-11-04 16:16 UTC, merged