S01US01 card activity html+css
WildCodeSchool/orleans-202109-php-projet-rocs pull request #28
Opened 2021-11-04 13:16 UTC by Bsir-Rachida

2021-11-04 13:22 UTC, cedric-pardon submitted a review, later dismissed

2021-11-04 14:52 UTC, sblondeau commented on src/View/Activity/index.html.twig
> +				<img src="assets/images/activity.jpg" class="img-fluid rounded-start" alt="...">
si tu ne veux pas mettre de alt, laisse vide `alt=""` et non `alt="..."`

2021-11-04 15:09 UTC, sblondeau requested changes

2021-11-09 16:22 UTC, cedric-pardon submitted a review, later dismissed

2021-11-09 16:40 UTC, sblondeau requested changes
il te reste des images versionnées dans assets/images
1. je pense qu'elle doivent etre dans uploads et donc non versionnées
2. si elles doivent rester là, il faut les réduire pour etre <200ko

2021-11-10 16:25 UTC, Halphane approved these changes

2021-11-12 07:53 UTC, sblondeau submitted a review, later dismissed

2021-11-13 09:11 UTC, Halphane commented
Tu as fait un merge de dev sur ta branche, c'est pas ouf, fait un git revert pour revenir à avant ce commit.
Ton code ne passe pas tous les test non plus.

2021-11-15 09:18 UTC, cedric-pardon approved these changes

2021-11-15 09:46 UTC, merged