cards doc fin
WildCodeSchool/orleans-202109-php-projet-rocs pull request #29
Opened 2021-11-04 13:19 UTC by cedric-pardon

2021-11-04 15:12 UTC, sblondeau requested changes
renomme tes fichiers à uploader pour enlever les espaces (JAMAIS d'espaces dans les noms de fichiers ! ;-) sinon tu vas avoir des soucis à un moment ou un autre)
tant qu'à les renommer, essaie que les noms soient cohérents aussi ;-)

2021-11-04 15:12 UTC, sblondeau commented on src/View/Membership/index.html.twig
> +		<p class="lh-lg">Possible à partir de 5 ans pour une licence du type loisir et à partir de 6 ans pour une
serait mieux que tu ajouter un line-height une bonne fois pour toute sur la balise p dans le fichier style.css plutot que de le rajouter 50fois dans ton fichier ;-)

2021-11-05 08:32 UTC, Bsir-Rachida approved these changes

2021-11-05 09:21 UTC, sblondeau approved these changes

2021-11-05 09:21 UTC, merged